# Site settings
title: Variety Pack
email: booking@varietypack.band
description: "Welcome to the webpage of the band Variety Pack."
baseurl: "https://varietypack.band"
url: "https://varietypack.band"

instagram_username: vpseattle

# Build settings
markdown: kramdown
