# Site settings
title: Variety Pack
email: contact@varietypack.band
description: "Welcome to the webpage of the band Variety Pack."
baseurl: "http://varietypack.band"
url: "http://varietypack.band"

instagram_username: vpseattle
facebook_username: varietypack.rockband

# Build settings
markdown: kramdown
